### ISSUE TITLE
2nd integration for labelbase-startos available.

### ISSUE THREAD

**Issue by xavierfiechter** [CasaVinteUm/labelbase-startos#10]
Just got informed by @remcoros that a 2nd integration for labelbase-startos was made available. Haven't tested it myself. 

<img width="596" alt="Screenshot 2024-07-29 at 00 53 34" src="https://github.com/user-attachments/assets/67bb597f-3c0a-4bf0-a3e8-241a8c222f77">

https://github.com/remcoros/labelbase-startos

**Comment by storopoli** [comment]
Yeah it would take me an eternity to figure this `docker_entrypoint.sh` https://github.com/remcoros/labelbase-startos/blob/5b694eb2ce7e32a3526755235567efd5d497ad2b/docker_entrypoint.sh

I will archive this and ask people to go to the @remcoros repo instead.
